FROM ebiven/vue-cli as build-env
MAINTAINER xiaoyukeji

COPY ./NodeApp/wapmanage /source/
WORKDIR /source
 
# 安装项目依赖包
RUN npm install xy-mint-ui --registry http://121.43.224.48:8000
RUN npm install chromedriver --chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver
RUN npm install --registry=https://registry.npm.taobao.org
RUN npm run build


FROM nginx
MAINTAINER xiaoyukeji

WORKDIR /app

#删除nginx 默认配置
RUN rm /etc/nginx/conf.d/default.conf

#添加我们自己的配置 default.conf 在下面
copy --from=build-env /source/nginx/default.conf /etc/nginx/conf.d/

#把刚才生成dist文件夹下的文件copy到nginx下面去
copy --from=build-env /source/dist /usr/share/nginx/html/

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

# 容器对外暴露的端口号
EXPOSE 5004/tcp