# 编译Docker镜像
FROM microsoft/aspnetcore-build as build-env
WORKDIR /source
COPY ./WebApp /source

WORKDIR /source/WapSite

RUN dotnet restore --verbosity q

RUN dotnet publish -c Release -o /source/publish

# 移动端镜像
FROM microsoft/aspnetcore
WORKDIR /app
copy --from=build-env /source/publish ./

#拷贝模板
copy --from=build-env /source/WapSite/Template ./Template

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

EXPOSE 5002/tcp

ENTRYPOINT ["dotnet", "WarrantyEnterpriseMobileStation.dll"]