# 编译Docker镜像
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build-env
WORKDIR /source
COPY ./source/WebApp /source

WORKDIR /source/ApiCenter
RUN dotnet restore --verbosity q

RUN dotnet publish -c Release -o /app

# WebApi端镜像
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
copy --from=build-env /app ./


#拷贝
copy --from=build-env /source/ApiCenter/qualitypics ./qualitypics

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

EXPOSE 5003/tcp

ENTRYPOINT ["dotnet", "WarrantyApiCenter.dll"]