# 编译Docker镜像
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build-env
MAINTAINER xiaoyukeji
WORKDIR /source
COPY ./source/WebApp /source

WORKDIR /source/WebSite

RUN dotnet restore --verbosity q

RUN dotnet publish -c Release -o /app

# PC端镜像
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
copy --from=build-env /app ./

#拷贝模板
copy --from=build-env /source/WebSite/Template ./Template
#拷贝Upload文件夹
copy --from=build-env /source/WebSite/UploadFile ./UploadFile

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

EXPOSE 5001/tcp

ENTRYPOINT ["dotnet", "WarrantyManage.dll"]