# 编译Docker镜像
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build-env
WORKDIR /source
COPY ./source/WebApp /source

WORKDIR /source/WapSite

RUN dotnet restore --verbosity q

RUN dotnet publish -c Release -o /app

# 移动端镜像
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
copy --from=build-env /app ./

#拷贝模板
copy --from=build-env /source/WapSite/Template ./Template

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

EXPOSE 5002/tcp

ENTRYPOINT ["dotnet", "WarrantyEnterpriseMobileStation.dll"]